export enum ErrorMessage {
  Default = 'DEFAULT',
  COURSE_LIST_DATABASE_EXCEPTION = 'COURSE_LIST_DATABASE_EXCEPTION',
  COURSE_GET_ONE_DATABASE_EXCEPTION = 'COURSE_GET_ONE_DATABASE_EXCEPTION',
  COURSE_LIST_BY_PAGE_DATABASE_EXCEPTION = 'COURSE_LIST_BY_PAGE_DATABASE_EXCEPTION',
  COURSE_SAVE_DATABASE_EXCEPTION = 'COURSE_SAVE_DATABASE_EXCEPTION',
  SCHEDULE_LIST_DATABASE_EXCEPTION = 'SCHEDULE_LIST_DATABASE_EXCEPTION',
  SCHEDULE_GET_ONE_DATABASE_EXCEPTION = 'SCHEDULE_GET_ONE_DATABASE_EXCEPTION',
  SCHEDULE_LIST_BY_PAGE_DATABASE_EXCEPTION = 'SCHEDULE_LIST_BY_PAGE_DATABASE_EXCEPTION',
  SCHEDULE_SAVE_DATABASE_EXCEPTION = 'SCHEDULE_SAVE_DATABASE_EXCEPTION',
}
