### Create
post http://development.eba-nip8saaw.us-east-1.elasticbeanstalk.com/course
Content-Type: application/json

{
    "title": "Angular",
    "level": "beginner"
}

### Get all
get http://development.eba-nip8saaw.us-east-1.elasticbeanstalk.com/course

### Get one
get http://development.eba-nip8saaw.us-east-1.elasticbeanstalk.com/course/1


### Update
put http://development.eba-nip8saaw.us-east-1.elasticbeanstalk.com/course/1
Content-Type: application/json

{
    "title": "NestJS",
    "level": "advanced"
}

### Delete
delete http://localhost:4010/course/1

### Get by page
get http://localhost:4010/course/page/2/size/5
